### ISSUE TITLE
3,3V Sensor

### ISSUE THREAD

**Issue by audi2010** [jp112sdl/HB-UNI-Sen-DIST-US#3]
Hallo Jérôme,
ich nutze den RCW-0001 Ultrasonic Sensor von ebay sensus-de. Der arbeitet auch mit 3,3 V.
Sieht aus wie der Grosse , ist aber in den Abmessungen kleiner.
Vielleicht kannst du das mal ergänzen.
![s-l1600](https://user-images.githubusercontent.com/31953947/70731019-51f15080-1d06-11ea-8713-dab8284e955e.jpg)

**Comment by jp112sdl** [comment]
628bed010f2a1267dca3c53ee17349af79e7b16e
